name: Assign Missing Dates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"  # auto-réassignation chaque nuit à 4h

jobs:
  assign_missing_dates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run assign_missing_dates.py
        run: |
          python assign_missing_dates.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add posts images posts_history.csv posts_pending images_pending
          git commit -m "Auto-assign missing dates" || echo "Aucun changement"
          git push || echo "Aucun changement"
