name: Daily Commit Post

on:
  schedule:
    - cron: "0 7 * * 1-5"   # Tous les jours Ã  07:00 du lundi au vendredi
  workflow_dispatch:

jobs:
  generate_and_commit_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pillow

      - name: Generate today's post
        run: |
          python generate_post.py

      - name: Commit post_du_jour.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add post_du_jour.md posts_history.csv
          git commit -m "Post du jour" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
